# \u539Flims \u6293\u53D6\u6837\u672C\u4F7F\u7528\uFF0C\u73B0\u5728\u6CA1\u6709\u4F7F\u7528\u5230
dbOne.jdbc.driver=oracle.jdbc.driver.OracleDriver
dbOne.jdbc.url=jdbc:oracle:thin:@192.168.20.212:1521:lims
dbOne.jdbc.username=gene
dbOne.jdbc.password=gene@lims2017

dbTwo.jdbc.driver=com.mysql.jdbc.Driver
# \u6D4B\u8BD5\u73AF\u5883
dbTwo.jdbc.url=jdbc:mysql://172.20.1.34:8806/omics?characterEncoding=utf-8
# \u751F\u4EA7\u73AF\u5883
# dbTwo.jdbc.url=jdbc:mysql://10.33.202.234:8806/omics?characterEncoding=utf-8
dbTwo.jdbc.username=novo
dbTwo.jdbc.password=GodIsLove

# lims \u6293\u53D6\u6837\u672C\u4F7F\u7528
dbThree.jdbc.driver=com.mysql.jdbc.Driver
dbThree.jdbc.url=jdbc:mysql://10.1.181.174:8808/novo_cancer?characterEncoding=utf-8
dbThree.jdbc.username=novo
dbThree.jdbc.password=novogene

# \u963F\u91CC\u4E91\u6570\u636E\u5E93\uFF0C\u6DFB\u52A0\u4E8C\u7EF4\u7801\u4F7F\u7528\uFF0C\u73B0\u5728\u6CA1\u6709\u4F7F\u7528\u5230
dbFour.jdbc.driver=com.mysql.jdbc.Driver
dbFour.jdbc.url=jdbc:mysql://47.94.106.94:3306/ngs?characterEncoding=utf-8
dbFour.jdbc.username=root
dbFour.jdbc.password=root263