dbOne.jdbc.driver=oracle.jdbc.driver.OracleDriver
dbOne.jdbc.url=jdbc:oracle:thin:@192.168.20.212:1521:lims
dbOne.jdbc.username=gene
dbOne.jdbc.password=gene@lims2017

dbTwo.jdbc.driver=com.mysql.jdbc.Driver
# \u6D4B\u8BD5\u73AF\u5883
# dbTwo.jdbc.url=jdbc:mysql://172.20.1.34:8806/omics?characterEncoding=utf-8
# \u751F\u4EA7\u73AF\u5883
dbTwo.jdbc.url=jdbc:mysql://127.0.0.1:8806/omics?characterEncoding=utf-8
dbTwo.jdbc.username=novo
dbTwo.jdbc.password=GodIsLove

dbThree.jdbc.driver=com.mysql.jdbc.Driver
dbThree.jdbc.url=jdbc:mysql://10.1.181.174:8808/novo_cancer_test?characterEncoding=utf-8
dbThree.jdbc.username=novo
dbThree.jdbc.password=novogene

dbFour.jdbc.driver=com.mysql.jdbc.Driver
dbFour.jdbc.url=jdbc:mysql://47.94.106.94:3306/ngs?characterEncoding=utf-8
dbFour.jdbc.username=root
dbFour.jdbc.password=root263