dbOne.jdbc.driver=oracle.jdbc.driver.OracleDriver
dbOne.jdbc.url=jdbc:oracle:thin:@192.168.20.212:1521:lims
dbOne.jdbc.username=gene
dbOne.jdbc.password=gene@lims2017


dbTwo.jdbc.driver=com.mysql.jdbc.Driver
# \u6D4B\u8BD5\u73AF\u5883
dbTwo.jdbc.url=jdbc:mysql://172.17.0.2:3306/omics?characterEncoding=utf-8

# \u751F\u4EA7\u73AF\u5883
# dbTwo.jdbc.url=jdbc:mysql://127.0.0.1:8806/omics?characterEncoding=utf-8
dbTwo.jdbc.username=novo
dbTwo.jdbc.password=GodIsLove


#dbThree.jdbc.driver=oracle.jdbc.driver.OracleDriver
#dbThree.jdbc.url=jdbc:oracle:thin:@172.17.8.106:1521/crm
#dbThree.jdbc.username=crm_zlsyb
#dbThree.jdbc.password=F45s383iJcv8
dbThree.jdbc.driver=com.mysql.jdbc.Driver
dbThree.jdbc.url=jdbc:mysql://10.1.181.174:8808/novo_cancer_test?characterEncoding=utf-8
dbThree.jdbc.username=novo
dbThree.jdbc.password=novogene


dbFour.jdbc.driver=com.mysql.jdbc.Driver
dbFour.jdbc.url=jdbc:mysql://47.94.106.94:3306/ngs?characterEncoding=utf-8
dbFour.jdbc.username=root
dbFour.jdbc.password=root263