cluster.host=172.30.1.2
cluster.username=tumor
cluster.password=passpassNovo2023

databases.host=127.0.0.1
databases.port=8806
databases.username=novo
databases.password=GodIsLove

local.host=127.0.0.1
local.username=cyc
local.password=xxxxxxx
