#cluster.host=192.168.50.3
#cluster.username=zhangxipeng
#cluster.password=cYts9SqoJvs85
#
#databases.host=172.20.7.65
#databases.port=3306
#databases.username=novo
#databases.password=GodIsLove
#
#local.host=127.0.0.1
#local.username=cyc
#local.password=xxxxxxx

#251
cluster.host=192.168.50.3
cluster.username=zhangxipeng
cluster.password=cYts9SqoJvs85

databases.host=172.20.1.251
databases.port=8806
databases.username=novo
databases.password=novogene

local.host=127.0.0.1
local.username=cyc
local.password=xxxxxxx